backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'posts'
    label: 'Post'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Data de publicação', name: 'date', widget: 'datetime' }
      - { label: 'Categoria', name: 'category', widget: 'string' }
      - { label: 'Capa', name: 'cover', widget: 'image', allow_multiple: false}
      - { label: 'Introdução', name: 'intro', widget: 'string', hint: 'Aparece somente na tela de listagem de posts e não no post em si', pattern: ['.{0,100}', "Deve ter no máximo 100 caracteres."] }
      - { label: 'Conteúdo', name: 'body', widget: 'markdown' }
